# Generated by Django 5.0.1 on 2024-01-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_hw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_name',
            field=models.CharField(default='default_img.jpeg', max_length=64),
        ),
    ]
