# Generated by Django 5.0.1 on 2024-01-31 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2_hw', '0004_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='sunny.png', upload_to=''),
        ),
    ]
